#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=4,walltime=00:30:00,vmem=8gb

profiles=$(jq -r .profiles config.json)

echo "Predicting PPCS from the mean FA tract profile of 47 white matter tracts..."
singularity exec -e docker://brainlife/dipy:1.4.1 python predict_ppcs.py -profiles $profiles


